version: "3.9"

services:
  mynote:
    container_name: mynote
    image: mynote
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    labels:
      - "traefik.http.routers.mynote.rule=Host(`mynote.navong.xyz`)"
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true
  postgres-network:
    external: true

volumes:
  postgres-data:
                